name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    - name: Style
      run: cargo +nightly fmt -- --check
    - name: Check and Clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
